
controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    # forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

    # fts_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - azimuth_joint
      - camera_joint
    interface_name: position

# fts_broadcaster:
#   ros__parameters:
#     interface_names.force.x: tcp_fts_sensor/force.x
#     interface_names.torque.z: tcp_fts_sensor/torque.z
#     frame_id: tool_link

# joint_broad:
#   ros__parameters: